makeitrealcamp/start

- app/controllers/password_resets_controller.rb
- app/controllers/passwords_controller.rb
> Fix error when someone opens a remote link in a different window/tab

- app/models/notification.rb
- app/views/notifications/_notification_badge_earned.html.erb
- app/views/notifications/_notification_comment_activity.html.erb
- app/views/notifications/_notification_comment_response.html.erb
- app/views/notifications/_notification_item.html.erb
- app/views/notifications/_resource_not_available.html.erb
- spec/features/notifications_spec.rb
> Fix error rendering notifications widget when a comment is deleted

- app/assets/stylesheets/notifications.scss
- app/assets/stylesheets/users.scss
- app/views/layouts/_navbar.html.erb
Al darle clic a los puntos o al badge, los llevará a un nuevo tab con el post del blog que explica lo de los niveles (mientras está lista esa sección).
> Nav users level

- app/models/project_solution.rb
- app/views/project_solutions/_form.html.erb
- spec/factories/project_solutions.rb
- spec/models/project_solution_spec.rb
> Add validation to url in ProjectSolution

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/challenges.scss
- app/helpers/courses_helper.rb
- fix #383, fix #386, fix #380
> fix some bugs

- app/views/project_solutions/_project_box.html.erb
- app/views/project_solutions/show.html.erb
- spec/features/project_solutions_spec.rb
- fix broken url of solution
- fix Display markdown of summary on  solution
> Fix bugs in project solution

- app/models/challenge.rb
- app/views/notifications/_notification_comment_activity.html.erb
- spec/features/notifications_spec.rb
> Redirect to discussion challenge in  notifications

- app/assets/javascripts/challenges.coffee
- app/assets/stylesheets/challenges.scss
- app/controllers/solutions_controller.rb
- app/models/solution.rb
- app/views/challenges/show.html.erb
- app/views/users/_level_js.html.erb
- lib/user_stats.rb
- spec/models/solution_spec.rb
> Fix bug of display level progess in evaluate challenge

- app/controllers/quizer/quiz_attempts_controller.rb
- spec/features/quiz_attempts_spec.rb
- spec/models/quizer/question_attempt_spec.rb
- spec/models/quizer/question_spec.rb
- spec/models/quizer/quiz_attempt_spec.rb
- spec/models/quizer/quiz_spec.rb
- Not show the results of a  quizz  when is being attempted by a user
>  Add some tests

- app/views/pages/curriculum.html.erb
- app/views/pages/faq.html.erb
- app/views/pages/home.html.erb
- app/views/pages/new_home.html.erb
- app/views/utils/_google_tagmanager.html.erb
Necesitamos arreglar esto @simon0191 @heyjoeb, para meter un código JS me tocó cambiar 4 archivos.
> Include Google tag manager code

- app/mailers/user_mailer.rb
- app/views/user_mailer/weekly_summary_email.html.erb
> fix some incorrect data in the weekly email

- app/controllers/pages_controller.rb
- app/views/pages/publicar.html.erb
- config/routes.rb
Se duplica el home por ahora para el landing de publicar.
> Added landing page for publicar.

- app/assets/stylesheets/challenges.scss
- app/views/challenges/show.html.erb
The preview button in challenges currently has broken css, this fixes with a normal btn-info style.
> Fix challenges preview button css

- Gemfile
- Gemfile.lock
- app/controllers/password_resets_controller.rb
- app/controllers/sessions_controller.rb
- app/forms/password_reset_request_form.rb
- spec/features/password_resets_spec.rb
- spec/features/sign_in_spec.rb
> 466 downcase email user

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/quizer/questions.scss
- app/controllers/quizer/questions_controller.rb
- app/views/quizer/questions/_question_row.html.erb
- app/views/quizer/questions/index.html.erb
Change rows background to white.
Order by creation date.
Remove the responsive table div.
> Improve question list in admin view

- app/assets/stylesheets/admin/challenges.scss
- app/helpers/admin/challenges_helper.rb
- app/views/admin/challenges/index.html.erb
The percentage is well calculated and ordered, the challenges that are not published are shown in gray.
> Solved percentage and color challenges

- evaluator_templates/express/executor.sh.erb
Remove the node_modules directory before npm install
> Fix express evaluator

- evaluator_templates/phantom/evaluator.js.erb
It was swallowing the errors of the page and some challenges passed without having to do anything.
> Fix PhantomJS evaluator

- evaluator_templates/phantom/evaluator.js.erb
- evaluator_templates/phantom/executor.sh.erb
Check that the server is up before running the evaluation. Also,
add timeout to PhantomJS itself.
> Improve PhantomJS evaluator

- app/views/admin/note_applicant_activities/create.js.erb
- app/views/admin/top_applicants/show.html.erb
- spec/features/admin/top_applicant_spec.rb
Added id to input field and added javascript to clear the input field
> Clear note-field on submit

- app/controllers/admin/projects_controller.rb
- app/controllers/projects_controller.rb
- app/models/project.rb
- app/views/admin/projects/index.html.erb
- app/views/layouts/navbar/_app.html.erb
- app/views/subjects/_projects_section.html.erb
- config/routes.rb
Crean una sección de Proyectos que den la posibilidad de crear nuevo proyecto, editar, eliminar y saber si esta publicado.
> Crear vista de Proyectos

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/sortable.coffee
- app/controllers/admin/challenges_controller.rb
- app/controllers/challenges_controller.rb
- app/views/admin/challenges/index.html.erb
- app/views/challenges/_embedded_files.html.erb
- app/views/shared/_challenge_actions.html.erb
- app/views/subjects/_challenges_section.html.erb
- config/routes.rb
- spec/controllers/resources_controller_spec.rb
- spec/features/notifications_spec.rb
- spec/features/resources_spec.rb
The admin can change the order of the challenges with the sortable component of jqueryUI
> sortable component ready to use

- app/controllers/pages_controller.rb
We need this to embed the form in the blog.
> Skip auth token to download guide

- app/controllers/admin/projects_controller.rb
- app/controllers/projects_controller.rb
- app/controllers/resources_controller.rb
- app/views/admin/challenges/index.html.erb
- app/views/admin/projects/index.html.erb
- app/views/resource_completion/create.js.erb
- app/views/resource_completion/destroy.js.erb
- app/views/resources/destroy.js.erb
- app/views/subjects/_resource_item.html.erb
- app/views/subjects/_resources_section.html.erb
- app/views/subjects/show.html.erb
- config/routes.rb
- spec/features/admin/quizzers_spec.rb
- spec/features/resources_spec.rb
Sortable component form JQUERY UI ready to use on challenges, resources and projects.
> challenges, projects and resources dragable ready

- app/assets/javascripts/slug.coffee
- app/controllers/webinars_controller.rb
- app/views/admin/webinars/index.html.erb
- app/views/admin/webinars/new.html.erb
- app/views/admin/webinars/show.html.erb
- app/views/pages_mailer/rsvp_webinar.html.erb
- config/routes.rb
1. Fix the length of the slug.
2. Create an attend route that is linked from the email.
> Apply some improvements to Webinars

- app/models/user.rb
- lib/tasks/mir.rake
Se corrige error que envia correo con actividad de la semana a los ususarios que no hacen ningun tipo de puntos a lo largo de la semana
Fix closes #889
> Minor fix for weekly email

- app/assets/stylesheets/admin/applicants.scss
- app/controllers/admin/top_applicants_controller.rb
- app/views/admin/top_applicants/index.html.erb
Se agrega paginacion a la vista de los aplicantes al curso top, de 100 registros por página
Fix closes #888
> Adding pagination to top applicants view

- app/assets/javascripts/course.coffee
- app/controllers/pages_controller.rb
- app/jobs/create_lead_job.rb
- app/mailers/admin_mailer.rb
- app/views/admin_mailer/new_lead.html.erb
- app/views/admin_mailer/new_scholarship.html.erb
- app/views/pages/_full_stack_becas_mujeres_registration.html.erb
- app/views/pages/_program_registration.html.erb
- app/views/pages/data_science_online.html.erb
- app/views/pages/full_stack_online.html.erb
- spec/features/pages_spec.rb
> Add source field to forms in landings

- app/assets/stylesheets/pages.scss
- app/assets/stylesheets/pages/_intro_to_python.scss
- app/controllers/pages_controller.rb
- app/views/pages/_intro_to_python_audience.html.erb
- app/views/pages/_intro_to_python_curriculum.html.erb
- app/views/pages/_intro_to_python_faqs.html.erb
- app/views/pages/intro_to_python.html.erb
- config/routes.rb
> Create free Python course landing

- app/views/pages/intro_to_js_interacpedia_mintic.html.erb
> Update interacpedia course time

- app/views/pages/innovate_peru.html.erb
> Update Innovate Landing dates

- app/views/pages/data_science_online.html.erb
> Update DS dates

- app/assets/stylesheets/pages/_data_science.scss
- app/assets/stylesheets/pages/_intro_to_js.scss
- app/controllers/pages_controller.rb
- app/views/pages/_full_stack_becas_mujeres_registration.html.erb
- app/views/pages/_program_registration.html.erb
- app/views/pages/_program_registration_free_course.html.erb
- app/views/pages/home.html.erb
- spec/features/pages_spec.rb
this closes #969 
- It adds the facebook meta tag domain validator that has been required lately to create custom conversions. 
- It adds the gender and birthday fields to every application form. The gender and birthday fields are required on every form to create impact reports for Nesst/Ikea
> Update gender field

- app/assets/javascripts/top_program.coffee.erb
- app/assets/stylesheets/pages/_innovate_peru.scss
- app/controllers/pages_controller.rb
- app/jobs/create_lead_job.rb
- app/models/top_applicant.rb
- app/views/layouts/navbar/_pages.html.erb
- app/views/pages/home.html.erb
- app/views/pages/top_full_and_part_time.html.erb
- config/routes.rb
- spec/controllers/pages_controller_spec.rb
- spec/features/pages_spec.rb
Implement:
- New TOP landing with partial and full time format options
- Update Lead creation with new fields
- Update UI of the modal form based on the user decisions while selecting. 
- Update specs 
- Update home link to web programs (to /top) and redirect /full-stack-online to /top
> 989 create toplandingpage

- app/helpers/admin/top_applicants_helper.rb
- app/views/admin/top_applicants/show.html.erb
Implements https://github.com/makeitrealcamp/start/issues/992
> Update top applicant CRM view

- app/views/pages/top_full_and_part_time.html.erb
> Update TOP landing dates

- config/routes.rb
- spec/features/pages_spec.rb
Closes https://github.com/makeitrealcamp/start/issues/1021 
Redirects scholarship and patreon landings to /top
> Redirects scholarship landings to TOP

- app/controllers/admin/top_applicants_controller.rb
In #1034 we called TopApplicant Model to list all applicants in search condition to display all applicants
Fixes #1034.
> Resolving search filter inside top applicants page

- app/controllers/admin/top_applicants_controller.rb
- app/models/innovate_applicant.rb
- app/models/top_applicant.rb
- app/views/admin/top_applicants/_modal.html.erb
- app/views/admin/top_applicants/edit.js.erb
> 1053 applicants placed graduated status

- app/controllers/admin/top_applicants_controller.rb
- app/models/top_applicant.rb
- app/views/admin/top_applicants/_applicant_details.html.erb
- app/views/admin/top_applicants/_modal.html.erb
- spec/features/admin/top_applicant_spec.rb
Adding new fields in applicant information like new salary, previous salary and socioeconomic level. Also, we added this information in applicant detail page
Fixes #1059
> Admin: Adding new fields in applicant information

- app/controllers/pages_controller.rb
- app/views/pages/_intro_to_html_audience.html.erb
- app/views/pages/_intro_to_html_curriculum.html.erb
- app/views/pages/_intro_to_html_faqs.html.erb
- app/views/pages/intro_to_html.erb
- config/routes.rb
Adds landing for Innpulsa free HTML and CSS course
> Add landing for HTML & CSS course

- app/controllers/pages_controller.rb
- config/routes.rb
Updated thank you page route to make it unique for this course and can measure conversions in facebook
> Update html and css course thankyou page route

- app/views/admin/top_applicants/index.html.erb
> Admin: removing tag in top applicants page

- app/assets/javascripts/mitic_program.coffee.erb
- app/assets/stylesheets/pages.scss
- app/assets/stylesheets/pages/_mitic_paraguay.scss
- app/views/pages/mitic_paraguay.html.erb
Adding changes on landing page
> Mitic paraguay

- app/assets/javascripts/mitic_program.coffee.erb
- app/assets/javascripts/top_program.coffee.erb
- app/controllers/admin/mitic_applicants_controller.rb
- app/controllers/admin/top_applicants_controller.rb
- app/models/applicant.rb
- app/views/admin/mitic_applicants/index.html.erb
- spec/features/pages_spec.rb
Admin: in this branch we added filters by substatus to admin view and change applicant date to allow only adults to apply
> Filters by substatus and restrict applicants age

- app/controllers/admin/innovate_applicants_controller.rb
- app/controllers/admin/mitic_applicants_controller.rb
- app/models/innovate_applicant.rb
- app/models/mitic_applicant.rb
- app/views/admin/innovate_applicants/_applicant_details.html.erb
- app/views/admin/innovate_applicants/_modal.html.erb
- app/views/admin/innovate_applicants/edit.js.erb
- app/views/admin/innovate_applicants/show.html.erb
- app/views/admin/innovate_applicants/update.js.erb
- app/views/admin/mitic_applicants/_applicant_details.html.erb
- app/views/admin/mitic_applicants/_modal.html.erb
- app/views/admin/mitic_applicants/edit.js.erb
- app/views/admin/mitic_applicants/show.html.erb
- app/views/admin/mitic_applicants/update.js.erb
- config/routes.rb
Adding button to add personal details of applicants
> Edit program functionality

- app/views/pages/top_full_and_part_time.html.erb
- app/views/top_invitations/_application.html.erb
In this commit we disabled tiempo completo option in select and changes dates
> changes in programa for program TOP

- app/controllers/admin/top_applicants_controller.rb
- app/models/top_applicant.rb
- app/views/admin/top_applicants/_modal.html.erb
- app/views/admin/top_applicants/index.html.erb
Admin: Adding in edit option the ability to change what program applicant want to assist and filters
> Changing Program format

- app/controllers/admin/webinars_controller.rb
- app/helpers/admin/webinars_helper.rb
- app/models/webinars/webinar.rb
- app/views/admin/webinars/_form.html.erb
- app/views/webinars/index.html.erb
- config/locales/es.yml
- db/migrate/20230111222739_add_category_to_webinars_webinars.rb
- db/schema.rb
In this branch we added events categories for different types of webinars. Adding webinar and workshop category we can disable recorded meeting
Fixes #1133
> Webinars category section

- app/controllers/top_program_controller.rb
- app/helpers/admin/top_applicants_helper.rb
- app/models/top_applicant.rb
- app/views/admin/top_applicants/_activity.html.erb
- app/views/admin/top_applicants/index.html.erb
We need to run in production a query to update all register in table called applicants with the value of 15 in the column called status when the value of the hstore column called info contains the key called "aspiring_course_accepted" and the value is equal to true
`UPDATE public.applicants SET status = 15 WHERE info @> hstore('aspiring_course_accepted', 'true');`
> Confirm course status

- app/controllers/admin/proinnovate_applicants_controller.rb
- app/controllers/pages_controller.rb
- app/jobs/create_lead_job.rb
- app/models/proinnovate_applicant.rb
- app/views/admin/proinnovate_applicants/_activity.html.erb
- app/views/admin/proinnovate_applicants/_applicant_details.html.erb
- app/views/admin/proinnovate_applicants/_modal.html.erb
- app/views/admin/proinnovate_applicants/edit.js.erb
- app/views/admin/proinnovate_applicants/index.html.erb
- app/views/admin/proinnovate_applicants/show.html.erb
- app/views/admin/proinnovate_applicants/update.js.erb
- app/views/layouts/navbar/_app.html.erb
- config/routes.rb
- spec/controllers/pages_controller_spec.rb
- spec/factories/proinnovate_applicants.rb
- spec/models/proinnovate_applicant_spec.rb
- Add Proinnovate 2004 batch to CRM 
- Configure COnvertLoop event
- Add rsepc
- Update states to fit Proinnovate requirements
> Add Proinnovate applicants functionalities

- app/controllers/pages_controller.rb
- app/views/admin/mitic_ai_applicants/show.html.erb
- app/views/admin/mitic_data_analysis_applicants/show.html.erb
- app/views/admin/mitic_serverless_applicants/show.html.erb
- app/views/admin/mitic_web3_applicants/show.html.erb
> Fix capture of document and document type
